version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: furniture_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"  # веб-интерфейс
      - "1025:1025"  # SMTP

volumes:
  postgres_data:
